name = "dj-webhooks"
main = "dist/index.js"
compatibility_date = "2025-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[vars]
ENVIRONMENT = "production"

# Webhook endpoint will be at webhooks.dj.current.space
[[routes]]
pattern = "webhooks.dj.current.space/*"
zone_name = "current.space"

# Development environment
[env.development]
name = "dj-webhooks-dev"
vars = { ENVIRONMENT = "development" }