# Cloudflare Worker Configuration - Points to actual worker in workers/api/
# This file tells Cloudflare where to find the actual worker configuration
name = "dj"
main = "workers/api/dist/index.js"
compatibility_date = "2025-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

# Production environment variables
[vars]
ENVIRONMENT = "production"

# Static assets configuration - serves React app from build output (modern approach)
[assets]
directory = "apps/web/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

# Custom domain routing
# Route already configured in Cloudflare dashboard - commenting to avoid duplicate error
# [[routes]]
# pattern = "dj.current.space/*"
# zone_name = "current.space"

# Build configuration for deployment
[build]
command = "pnpm run build:worker"

# Development environment override
[env.development]
name = "dj-dev"
workers_dev = true
vars = { ENVIRONMENT = "development" }