# Cloudflare Worker Configuration - Points to actual worker in workers/api/
# This file tells Cloudflare where to find the actual worker configuration
name = "dj"
main = "workers/api/dist/index.js"
compatibility_date = "2025-09-23"
compatibility_flags = ["nodejs_compat"]

# Production environment variables
[vars]
ENVIRONMENT = "production"
FRONTEND_URL = "https://dj.current.space"

# Static assets configuration - serves React app from build output (modern approach)
[assets]
directory = "apps/web/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
# CRITICAL: Run Worker first for API routes (otherwise static assets take precedence)
run_worker_first = ["/api/*"]

# Build configuration for deployment
[build]
command = "pnpm run build:worker"

# Development environment override
[env.development]
name = "dj-dev"
workers_dev = true
vars = { ENVIRONMENT = "development" }