# Cloudflare Worker Configuration for DJ App
name = "dj"
main = "dist/index.js"
compatibility_date = "2025-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

# Production environment variables
[vars]
ENVIRONMENT = "production"

# Static site configuration - serves React app from build output
[site]
bucket = "../../apps/web/dist"

# Custom domain routing
# Route already configured in Cloudflare dashboard - commenting to avoid duplicate error
# [[routes]]
# pattern = "dj.current.space/*"
# zone_name = "current.space"

# Build configuration for deployment
[build]
command = "cd ../.. && pnpm run build:worker"
watch_dir = ["src", "../../packages", "../../apps/web/src"]

# Development environment override
[env.development]
name = "dj-dev"
workers_dev = true
vars = { ENVIRONMENT = "development" }